version: 25
jobs:
- name: qiniu
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: 创建容器
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_path@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 创建账号
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - pwd
      - qshell account @property:qiniu_ac@ @property:qiniu_ak@ qiniu
      - qshell qupload2 --bucket aboutme-txg --src-dir=./ --skip-file-prefixes=.gitignore,.onedev-buildspec.yml --skip-path-prefixes=.git  --overwrite
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: 同步到 github
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 同步到 github
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - git rm -r --cached .
      - git add .
      - git commit -m 'update .gitignore'
      - git -c http.proxy=@property:proxy_url@ -c https.proxy=@property:proxy_url@ push --force https://txgde-space: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@@github.com/txgde-space/shell-style-personal-page.git
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
