version: 25
jobs:
- name: qiniu
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: 创建容器
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_path@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 创建账号
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - pwd
      - qshell account @property:qiniu_ac@ @property:qiniu_ak@ qiniu
      - qshell qupload2 --bucket aboutme-txg --src-dir=./ --skip-file-prefixes=.gitignore,.onedev-buildspec.yml --skip-path-prefixes=.git  --overwrite
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: 同步到在线git 仓库
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 设定 git 信息
    runInContainer: true
    image: git
    interpreter: !DefaultInterpreter
      commands:
      - git config --global user.email @property:email@
      - git config --global user.name @property:username@
      - git rm .onedev-buildspec.yml
      - git commit -m 'update'
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 同步到 github
    runInContainer: true
    image: git
    interpreter: !DefaultInterpreter
      commands:
      - git -c http.proxy=@property:proxy_url@ -c https.proxy=@property:proxy_url@ push --force https://txgde-space:@secret:github_token@@@github.com/txgde-space/shell-style-personal-page.git
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 同步到 gitee
    runInContainer: true
    image: git
    interpreter: !DefaultInterpreter
      commands:
      - git push --force https://txgde-space:@secret:gitee_secret@@@gitee.com/txgde_space/shell-style-personal-page.git
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
