version: 25
jobs:
- name: qiniu
  jobExecutor: docker
  steps:
  - !RunContainerStep
    name: 创建容器
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_path@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 创建账号
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - qshell account jCqlDDtKrsCSck-4s5BEd6vQHtSCiF15G6lMTk3i mF2Kbj5zT8CuOP69gs2lhu-oJtJ-ATxbL8KOYCPU qiniu
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 查看是否成功
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - qshell user ls >> log.txt
      - cat log.txt
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 同步对象存储
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - qshell qupload2 --bucket aboutme-txg --src-dir=/home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: test
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: qiniu_docker
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_name@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - ls -hl ./
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - ls /
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
