version: 25
jobs:
- name: qiniu
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: 创建容器
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_path@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: 创建账号
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - pwd
      - qshell account jCqlDDtKrsCSck-4s5BEd6vQHtSCiF15G6lMTk3i mF2Kbj5zT8CuOP69gs2lhu-oJtJ-ATxbL8KOYCPU qiniu
      - qshell qupload2 --bucket aboutme-txg --src-dir=./ --skip-file-prefixes=.gitignore,.onedev-buildspec.yml --skip-path-prefixes=.git  --overwrite
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: test
  jobExecutor: docker
  steps:
  - !CheckoutStep
    name: check
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: qiniu_docker
    image: qiniu_ubuntu
    volumeMounts:
    - sourcePath: '@project_name@'
      targetPath: /home
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - ls -hl ./
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: test
    runInContainer: true
    image: qiniu_ubuntu
    interpreter: !DefaultInterpreter
      commands:
      - ls /
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: 同步到 github
  jobExecutor: docker
  steps:
  - !PushRepository
    name: 同步到 github
    remoteUrl: https://github.com/txgde-space/shell-style-personal-page.git
    certificate: "-----BEGIN OPENSSH PRIVATE KEY-----\r\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn\r\nNhAAAAAwEAAQAAAYEAxQSC4xqFLG6lx9OUQrKQ+FlUp2/QSXorTDs0GKu+mymlzSMA3uST\r\nCucYFM0er+gbsSD5Whbpb+L/Frhe6wk5jvgrzwbsSiDiA4jRGFizSJCrA4UKj+6L2fNQFq\r\nwQPBJ6K5v3khLtmzonaj8qz9EoU36NQfoOvlgtD+wVSqstU9m0DWnss2njFWkwPxbZQLAs\r\nOibsp/tB1PvKTKYo10bBNzmtf8B71cU9agnUNas3YSG4LsN7o0P19hiWpnBYZSrg2oTI5/\r\n7PSkqXaGk4Ug3BDvWHQd+/LcV/jEziNigT1tVH3X1A+d2dyvWfzt3FwPGVs45V7xIQ322o\r\n0QenTQO8cCmkKxfnPeUInitQNsQ8QeYzQuMqV0w5L+e9TXNRAgb8QQw7mYrkNo/V4Z1weN\r\nFU8k3mIVokdKQAC8nx5suy8AgTdWSJ5eL4haJs5Wr3A0i60UYIlTlHYI4EUbwM7yByqN3B\r\nBcOObWWZLu1Yp9D3XDunzHOaBPrSJlAAluMWJMNTAAAFmGOn+gxjp/oMAAAAB3NzaC1yc2\r\nEAAAGBAMUEguMahSxupcfTlEKykPhZVKdv0El6K0w7NBirvpsppc0jAN7kkwrnGBTNHq/o\r\nG7Eg+VoW6W/i/xa4XusJOY74K88G7Eog4gOI0RhYs0iQqwOFCo/ui9nzUBasEDwSeiub95\r\nIS7Zs6J2o/Ks/RKFN+jUH6Dr5YLQ/sFUqrLVPZtA1p7LNp4xVpMD8W2UCwLDom7Kf7QdT7\r\nykymKNdGwTc5rX/Ae9XFPWoJ1DWrN2EhuC7De6ND9fYYlqZwWGUq4NqEyOf+z0pKl2hpOF\r\nINwQ71h0Hfvy3Ff4xM4jYoE9bVR919QPndncr1n87dxcDxlbOOVe8SEN9tqNEHp00DvHAp\r\npCsX5z3lCJ4rUDbEPEHmM0LjKldMOS/nvU1zUQIG/EEMO5mK5DaP1eGdcHjRVPJN5iFaJH\r\nSkAAvJ8ebLsvAIE3VkieXi+IWibOVq9wNIutFGCJU5R2COBFG8DO8gcqjdwQXDjm1lmS7t\r\nWKfQ91w7p8xzmgT60iZQAJbjFiTDUwAAAAMBAAEAAAGBAKYcX57LRW1o/S22HlL962z5JH\r\n7nr13EO61SXWJPq613N+v1j05euft/TLZ9G1qFAJQfkR18I+XKJfkqCh1w8a6xX351/9Og\r\nVe9U87brUn3kO8wD6BvirNdeZjA3cpizm34ZSmtGuj8ekQzrpVUCrFV5ZfAyvSuPfK7oBi\r\numl9kSvNRycrfylxv+TEdlJFd+Mkv1daNMHP1OLgriLZ0UcuP1JWuJBt/+JQG6t8loSpEC\r\ntR/4gc3uBvsvUBWUs3LY6rA3kovKW+YBLVUjlR770dDuUpkd+MmALeAO4vzefzyGi2W7l/\r\nF9y7MNzYG986fcFLBD7LqNyAPsN5a8fyBJBFxBdJT97nxQF/2RCapOUGiCQaCJQ5bmoaIl\r\ncfOyNaggiRsmEqYFmVrOuuwu1aEPIMKfcAa2yK59AnwZqVaAgiwfWECSpjLTzwdcFrSbc/\r\nIxC9fRs4vQI7a/X+KIlC61EVA/jE6tx18PbZTHKABtPo1Hr4Hc84OPgC/502O8bQLugQAA\r\nAMBX+pNTgsw4bKGtlYdD8+hrqqF4WubxMYpMO1zJXSvxE6cjai1Fd1mesh7U0rVpB3k78b\r\nUmf9Dr7qbWGL/Zb8ZPKDTbRdvopYzTilaaLWwgZ+FU1lTgQHuBFR+YOWVd42RZdNwjmseC\r\nEonU4GiHvhwVprUSc3MPLBHDouUvvm3rZ8bccma+r2IeHieupY8KZ4FDadvUjOxRuBGG2B\r\nFRjMN9spvbIWHTZrVCvj7dV0gAlKfRu+4PYd8CqWG5WNcn3HsAAADBAPTBVtv2OxudkjAn\r\naN3EO7JHMF0xCkcm9e6hw2+jtPDVG2WMV1nufE1zTPZYtXsvnaiM2LkZu/cuaPKj9jmg1T\r\n6xznnZviMHLBZkxHGwYIBaSmJ8CLzo0ZSBmvzfQViaI8icprEEiGrIy8WzXQON98z9RwR8\r\naZMgor4rgtM4/1uUbHNkVuTOjm6iZ5RiCY1XsKtrU8c2Qpyb31pVVdhRq1pyrpF3r/e2zP\r\nVTny5e6uG5fW7jWUtD3hlCu1tzjhNM2QAAAMEAzhG2J5+UEceUZ7tLkbYmwMox8XeCfxhx\r\nhfZreu/ft+dN4Vr2iVXsANG/tFRWL19SKYGreTqzfHucN9e2IZ5CAyX+bsaTlDhjdCCA5Q\r\nbWILbR2NQUcdSFZxssBSvU1KZmaG2XJnUW93A1m8bIZ32LsJmWhcModEvzErSJKyyWY6Gz\r\n1RDiN3rspq6jNI9Ri0RnxGNFXYGFDG2vPidqhLu6RbRKBW3BHqmWWgvlZaEM6V/ldOSfT1\r\n1QyYMeLZyZAmYLAAAAHHJvb3RAaVowamwwYmI1cTZpNmU2dWp6NDVrcloBAgMEBQY=\r\n-----END OPENSSH PRIVATE KEY-----"
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    paths: -.onedev-buildspec.yml
    projects: shell-style-personal-page
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
